site_name: AARC Docs test # Head title
theme:
  name: material
  language: en 
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    admonition: # Show in warnings and announcements
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
  # Navigation references : https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/
    - navigation.instant # Enable Instant Load
    - navigation.instant.prefetch # Get the page when hovering over a link
    - navigation.instant.progress # Show progress as it loads
    - navigation.tabs # Show tabs under headers (per markdown document)
    - navigation.path # Show depth of document
    - navigation.top # Back to top button
    - toc.follow # Enable sidebar anchors
    - toc.integrate # The Table of Content is rendered in the left sidebar.
    - search.suggest # Search suggestions feature
    - search.highlight # Highlighting links

  # Codeblock references : https://squidfunk.github.io/mkdocs-material/reference/code-blocks/?h=code
    - content.code.copy # Create a copy button in a code block
    - content.code.annotate # Show lines in code blocks, use random content
    - content.tabs.link # ??..
  palette:  
    # Color references : https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    # Setting a dark mode button in the header
    - media: "(prefers-color-scheme: light)" # Depending on your system settings 
      scheme: default # Light mode color(=white)
      primary: blue grey # Header color
      accent: indigo # Hovered links, buttons and scrollbars color
      toggle: # Toggle background color button in header
        icon: material/brightness-7 
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate # Dark mode color
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - index.md 
  - getting_started.md
  - example.md

plugins:
  - search
  
markdown_extensions:
  - pymdownx.mark # Background Emphasis
  - admonition # Admonition references : https://squidfunk.github.io/mkdocs-material/reference/admonitions/
  - pymdownx.details
  - pymdownx.superfences
  - footnotes # Footnotes references : https://squidfunk.github.io/mkdocs-material/reference/footnotes/#fn:1
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  